uploads = []

[[generated]]
id = "RNgq2Oi-c1wcZaIGhxOEm"
uri = "file://artifacts/nt-web-design/public/portfolio/proj-restaurant.png"
type = "image"
title = "generated_image"

[[generated]]
id = "t__lhdM0EgT7RvL3heQzw"
uri = "file://artifacts/nt-web-design/public/portfolio/proj-ecommerce.png"
type = "image"
title = "generated_image"

[[generated]]
id = "EojSdp4tAjdSlfjWyaNTu"
uri = "file://artifacts/nt-web-design/public/portfolio/proj-saas.png"
type = "image"
title = "generated_image"

[[generated]]
id = "tqivpa9r7Y6kKpOfeEVWv"
uri = "file://artifacts/nt-web-design/public/portfolio/proj-law.png"
type = "image"
title = "generated_image"

[[generated]]
id = "piKtZcRVp1VRleuldakky"
uri = "file://artifacts/nt-web-design/public/portfolio/proj-fitness.png"
type = "image"
title = "generated_image"

[[generated]]
id = "UuCMONRCwevlEnhcrWFAg"
uri = "file://artifacts/nt-web-design/public/portfolio/proj-realestate.png"
type = "image"
title = "generated_image"

[[generated]]
id = "oaJo_03EDNsLNUQH2quF8"
uri = "file://artifacts/nt-web-design/public/portfolio/proj-startup.png"
type = "image"
title = "generated_image"

[[generated]]
id = "i9YZfLY5D0QYhZmepfcls"
uri = "file://artifacts/nt-web-design/public/portfolio/proj-medical.png"
type = "image"
title = "generated_image"

[[generated]]
id = "fosdbnIuxijnIbBjSGUE6"
uri = "file://artifacts/nt-web-design/public/portfolio/proj-photography.png"
type = "image"
title = "generated_image"

[[generated]]
id = "koJ_9QE9q6PfSagB8dXij"
uri = "file://artifacts/nt-web-design/public/portfolio/proj-construction.png"
type = "image"
title = "generated_image"

[[generated]]
id = "XE8qYZpTGGTPA5MPgY1eW"
uri = "file://artifacts/nt-web-design/public/portfolio/proj-audreyrh.png"
type = "image"
title = "generated_image"

[[outputs]]
id = "j2PlJ8cDdUPKISm5Im8pE"
uri = "file://artifacts/nt-web-design/public/favicon.svg"
type = "image"
title = "New Favicon — NT mark, white on black"
