// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/colour-themes/Amber.tsx": () => import("../components/mockups/colour-themes/Amber.tsx"),
  "./components/mockups/colour-themes/Cyan.tsx": () => import("../components/mockups/colour-themes/Cyan.tsx"),
  "./components/mockups/colour-themes/Emerald.tsx": () => import("../components/mockups/colour-themes/Emerald.tsx"),
  "./components/mockups/colour-themes/MidnightBlue.tsx": () => import("../components/mockups/colour-themes/MidnightBlue.tsx"),
  "./components/mockups/colour-themes/Rose.tsx": () => import("../components/mockups/colour-themes/Rose.tsx")
};
