kind = "web"
previewPath = "/"
title = "NT Web Design"
version = "1.0.0"
id = "artifacts/nt-web-design"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
localPort = 25715
name = "web"
paths = ["/"]

[services.development]
run = "pnpm --filter @workspace/nt-web-design run dev"

[services.env]
PORT = "25715"
BASE_PATH = "/"

[services.production]
build = ["pnpm", "--filter", "@workspace/nt-web-design", "run", "build"]
publicDir = "artifacts/nt-web-design/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"
